apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: nodetop
spec:
  version: {{ .TagName }}
  homepage: https://github.com/rajatjindal/kubectl-nodetop
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-nodetop/releases/download/{{ .TagName }}/kubectl-nodetop_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-nodetop
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-nodetop/releases/download/{{ .TagName }}/kubectl-nodetop_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-nodetop
  shortDescription: Display resource (CPU/memory) usage of pods grouped by nodes